
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: npm install
    - run: npm run build
    
    # Adjustments to fix base path in index.html
    - name: Fix base path in index.html
      run: |
        cd dist
        sed -i 's|<base href="/">|<base href="/">|g' index.html
    
    # Configure GitHub Pages deployment
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: www.fornodacacau.com.br
